image: moodlehq/moodle-workplace-plugin-ci:7.3

services:
- postgres:9.6
#- mysql:5.7.26
- name: selenium/standalone-chrome:3
  alias: selenium-standalone-chrome

variables:
  MOODLE_REPO: git@git.in.moodle.com:workplace/workplacedev.git
  MOODLE_BRANCH: master
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB: "pgsql"
#  DB: "mysqli"

before_script:
- . prepare-workplace $cibot_sshkey
- cd $CI_PROJECT_DIR/..
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_tenant.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-theme_workplace.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_program.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_certification.git
- moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
- php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
- cd moodle

jobtest:
  script:
  - php admin/tool/phpunit/cli/init.php
  - . check-start
  - . check workplace_copyrights_and_licenses
  - . check this_plugin_is_part_of "Moodle Workplace https://moodle.com/workplace based on Moodle" --wplicensecomment
  - . check version_number
  - . check language_file_sorting
  - . check moodle-plugin-ci phplint
  - . check moodle-plugin-ci phpcpd
  - . check moodle-plugin-ci phpmd
  - . check moodle-plugin-ci codechecker --max-warnings 0
  - . check moodle-plugin-ci phpdoc
  - . check moodle-plugin-ci validate
  - . check moodle-plugin-ci savepoints
  - . check moodle-plugin-ci mustache
  - . check moodle-plugin-ci grunt --max-lint-warnings 0
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v admin/tool/dataprivacy/tests/metadata_registry_test.php
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v lib/tests/externallib_test.php
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v privacy/tests/provider_test.php
  - . check moodle-plugin-ci phpunit --coverage-text
  - . check moodle-plugin-ci behat --suite workplace --profile chrome
  - . check-finish
  except:
  - tags
